#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

#define ABSENT -1
#define READABLE_FIELDS_MASTER 2
#define READABLE_FIELDS_SLAVE 4
#define REQUIRED_FIELDS_MASTER 1
#define REQUIRED_FIELDS_SLAVE 3
#define MODIFIABLE_FIELDS_MASTER 1
#define MODIFIABLE_FIELDS_SLAVE 2
#define STRING_LENGTH 50
#define TRASH_CAPACITY 5

#endif